In [ ]:
import numpy as np
data=np.array([1,2,3,4,5,6,7,8,9,10])
print(data)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
import numpy as np
data=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(data.shape)



(3, 3)


In [ ]:
import numpy as np
data=np.array([2,4,6,8])
mul=np.prod(data)
print(mul)

384


In [ ]:
import numpy as np
data=np.array([1,2,3,4,5,6,7,8,9,10])
sum=np.sum(data)
print(sum)

55


In [ ]:
import numpy as np
data=np.array([1, 3, 5, 7, 9])
for i in data:
    print(i**2)

1
9
25
49
81


In [ ]:
import numpy as np
data=np.array([10, 20, 30, 40, 50])
min=np.min(data)
max=np.max(data)
print("min:",min)
print("max:",max)

min: 10
max: 50


In [ ]:
import numpy as np
data=np.array([[2, 4], [6, 8], [10, 12]])
print(data.reshape(2,3))

[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
import numpy as np

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_sums = np.sum(data, axis=1)
column_sums = np.sum(data, axis=0)

print("Sum of each row:", row_sums)
print("Sum of each column:", column_sums)


Sum of each row: [ 6 15 24]
Sum of each column: [12 15 18]


In [ ]:
import numpy as np

data = np.array([5, 10, 15, 20, 25, 30])
even = data[data%2==0]

print("Even:", even)

Even: [10 20 30]


In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])
sum = np.cumsum(data)

print("Sum:", sum)

Sum: [ 1  3  6 10 15]


In [ ]:
import numpy as np
data = np.array([1, 4, 9, 16, 25])
sqrt=np.sqrt(data)
print("sqrt:",sqrt)

sqrt: [1. 2. 3. 4. 5.]


In [ ]:
import numpy as np
data = np.array([5, 10, 15, 20, 25, 30])
find=np.where(data==20)
print("Find:",find)

Find: (array([3]),)


In [ ]:
import numpy as np
data = np.array([[1,2],[3,4],[5,6]])
print(data.shape)


(3, 2)


In [5]:
import numpy as np
data = np.array([[3, 12, 17,  6],
 [15,  8, 14, 11],
 [2, 19, 16, 7],
 [13, 18, 5, 10]]
)

data[data%2==0]=0
print(data)

[[ 3  0 17  0]
 [15  0  0 11]
 [ 0 19  0  7]
 [13  0  5  0]]


In [17]:
import numpy as np
data = np.array([
    [15, 28, 32, 42, 11],
    [38, 27, 19, 22, 30],
    [45, 12, 24, 31, 40],
    [20, 35, 18, 14, 48],
    [29, 33, 26, 37, 16]
])

mean=data.mean()
median=np.median(data)
stddev=data.std()
print("Mean: ",mean)
print("Median: ",median)
print("Standard Deviation: ",stddev)

Mean:  27.68
Median:  28.0
Standard Deviation:  10.329453034890086
